version: '2'
services:
  grafana:
    # Full tag list: https://hub.docker.com/r/grafana/grafana/tags/
    image: "public.ecr.aws/bitnami/grafana:6.7.4"
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - monitoring
    links:
      # Grafana requires network access to InfluxDB
      - influxdb
    ports:
      # The WebUI for grafana is served on port 3000
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - ./6wind-logo.svg:/opt/bitnami/grafana/public/img/grafana_icon.svg:rw
      - ./6wind-logo.svg:/opt/bitnami/grafana/public/app/plugins/datasource/loki/img/grafana_icon.svg:rw
      - ./6wind-logo.svg:/opt/bitnami/grafana/public/img/grafana_com_auth_icon.svg:rw
      - ./6wind-logo-semiwhite.svg:/opt/bitnami/grafana/public/img/grafana_typelogo.svg:rw
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: "public.ecr.aws/influxdb/influxdb:1.7.10"
    container_name: influxdb
    networks:
      - monitoring
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
networks:
  monitoring:
