#!/bin/bash
# Copyright 2018 6WIND S.A.
# Tool to start a monitoring testbed.
#
# deps: python-requests3 docker-compose

CONF_DIR="./tools/confs"

usage()
{
	echo "Usage: $0 [conf_file]" 1>&2;
	echo "Existing configuration file are:" 1>&2;
	echo "$(find $CONF_DIR -type f)" 1>&2;
	exit 1; 
}

if [ -z "${1}" ] || ! [ -f $1 ]; then
	usage
fi

# Start grafana/influxdb
docker-compose up -d

# Configure grafana according to provided yml configuration file
tools/configure_grafana.py $(realpath $1)

# hack to display 6WIND logo
docker exec -i grafana bash -c "sed -i 's,sidemenu__logo img{width:30px,sidemenu__logo img{width:130px,' ./public/build/grafana.light.*.css"
docker exec -i grafana bash -c "sed -i 's,\.sidemenu{\(.*\);width:60px,\.sidemenu{\1;width:160px,' ./public/build/grafana.light.*.css"
docker exec -i grafana bash -c "sed -i 's,\.login-logo{,.login-logo{max-height:0;,' ./public/build/grafana.light.*.css"
docker exec -i grafana bash -c "sed -i 's,\.login-logo{,.login-logo{max-height:0;,' ./public/build/grafana.dark.*.css"

echo
echo "Go to http://localhost:3000 for Grafana dashboard (admin/admin)"
